---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rhpds/ocp-cluster-addons
    targetRevision: main
    path: rhoai
    helm:
      values: |
        operator:
          namespace: redhat-ods-operator
          startingCSV: rhods-operator.2.10.0
          installPlanApproval: Manual
        datasciencecluster:
          components:
            codeflare:
              managementState: Managed
            dashboard:
              managementState: Managed
            datasciencepipelines:
              managementState: Managed
            kserve:
              managementState: Managed  
            kueue:
              managementState: Managed
            modelmeshserving:
              managementState: Managed
            ray:
              managementState: Managed
            workbenches:
              managementState: Managed
        helper-status-checker:
          approver: true
          checks:
            - operatorName: rhods-operator
              namespace:
                name: redhat-ods-operator
              syncwave: '1'
              serviceAccount:
                name: "rhoai-status-checker"
  destination:
    namespace: redhat-ods-operator
    server: https://kubernetes.default.svc
  syncPolicy: {}
