---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/juliaaano/ocp-cluster-addons
    targetRevision: main
    path: devspaces
    helm:
      values: |
        namespace: openshift-operators
        operator:
          startingCSV: devspacesoperator.v3.15.0
          installPlanApproval: Manual
        helper-status-checker:
          approver: true
          checks:
            - operatorName: devspaces
              namespace:
                name: openshift-operators
              syncwave: '1'
              serviceAccount:
                name: "devspaces-status-checker"
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  syncPolicy: {}
