---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    openshift.io/description: "Red Hat OpenShift AI Operator"
    openshift.io/display-name: "RHOAI Operator"
