{{ if .Values.operator.install -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operator.namespace }}
  annotations:
    openshift.io/display-name: "GitOps Operator"
    openshift.io/description: "Red Hat OpenShift GitOps Operator"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
spec:
  channel: {{ .Values.operator.channel }}
  installPlanApproval: {{ .Values.operator.installPlanApproval }}
  name: {{ .Values.operator.name }}
  source: {{ .Values.operator.source }}
  sourceNamespace: {{ .Values.operator.sourceNamespace }}
  {{- if .Values.operator.startingCSV }}
  startingCSV: {{ .Values.operator.startingCSV }}
  {{- end }}
{{- end }}
