{{- range .Values.clients }}
{{- $clientRealm := .realm }}
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ .clientId }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      {{- $matchLabels := dict }}
      {{- range $.Values.realms }}
        {{- if eq .name $clientRealm }}
          {{- $matchLabels = .labels }}
        {{- end }}
      {{- end }}
      {{- range $key, $value := $matchLabels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  client:
    clientId: {{ .clientId }}
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    redirectUris:
      - "{{ .redirectUri }}"
    defaultClientScopes:
    - profile
    - email
    - roles
    - acr
    - web-origins
{{- end }}
