---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: {{ .Values.keycloak.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- range $key, $value := .Values.keycloak.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  instances: 1
  externalAccess:
    enabled: True
