---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    openshift.io/description: "Red Hat Single Sign-On Namespace"
    openshift.io/display-name: "RHSSO Namespace"
