---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: {{ .Values.realm.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
spec:
  realm:
    id: "{{ .Values.realm.name }}"
    realm: "{{ .Values.realm.name }}"
    enabled: True
    displayName: "{{ .Values.realm.displayName }}"
  instanceSelector:
    matchLabels:
      {{- range $key, $value := .Values.keycloak.labels }}
      {{ $key }}: {{ $value }}
      {{- end }}
