{{- range .Values.users }}
{{- $clientRealm := .realm }}
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: {{ .username }}
spec:
  realmSelector:
    matchLabels:
      {{- $matchLabels := dict }}
      {{- range $.Values.realms }}
        {{- if eq .name $clientRealm }}
          {{- $matchLabels = .labels }}
        {{- end }}
      {{- end }}
      {{- range $key, $value := $matchLabels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  user:
    username: {{ .username }}
    credentials:
      - type: password
        value: {{ .password }}
    email: {{ .email }}
    emailVerified: true
    enabled: true
{{- end }}
