{{- range .Values.users }}
{{- $clientRealm := .realm }}
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: {{ .username }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  realmSelector:
    matchLabels:
      {{- $matchLabels := dict }}
      {{- range $.Values.realms }}
        {{- if eq .name $clientRealm }}
          {{- $matchLabels = .labels }}
        {{- end }}
      {{- end }}
      {{- range $key, $value := $matchLabels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  user:
    username: {{ .username }}
    credentials:
      - type: password
        value: {{ .password }}
    email: {{ .email }}
    emailVerified: true
    enabled: true
{{ if .admin }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-rhsso-{{ .username }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .username }}
{{- end }}
{{- end }}
