{{- range .Values.apis }}
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: "{{ .name }}"
  systemName: "{{ .name }}"
  privateBaseURL: "{{ .backend.privateBaseURL }}"
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: "{{ .name }}"
  systemName: "{{ .name }}"
  backendUsages:
    {{ .name }}:
      path: {{ .backend.path }}
  {{- $sections := dict
    "deployment" .deployment
    "policies" .policies
    "methods" .methods
    "mappingRules" .mappingRules
  -}}
  {{- range $key, $value := $sections }}
  {{- if $value }}
  {{ $key }}:
    {{- toYaml $value | nindent 4 }}
  {{- end }}
  {{- end }}
  applicationPlans:
    standard:
      name: "Standard Plan"
      published: true
---
apiVersion: capabilities.3scale.net/v1beta1
kind: ActiveDoc
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: "{{ .name }}"
  activeDocOpenAPIRef:
    url: {{ .activeDocOpenAPIRef }}
  skipSwaggerValidations: true
  productSystemName: {{ .name }}
  published: true
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-pwd
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
stringData:
  password: {{ .name }}
---
apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  orgName: "{{ .name }}"
---
apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  username: {{ .name }}
  email: {{ .name }}@domain.com
  role: admin
  passwordCredentialsRef:
    name: {{ .name }}-pwd
  developerAccountRef:
    name: {{ .name }}
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  name: {{ .name }}
  description: "Default application for {{ .name }}"
  applicationPlanName: standard
  productCR:
    name: {{ .name }}
  accountCR:
    name: {{ .name }}
---
apiVersion: capabilities.3scale.net/v1beta1
kind: ProxyConfigPromote
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  productCRName: {{ .name }}
  production: true
  deleteCR: false
{{- end }}
