{{ if .Values.apimanager.removeBearer -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apimanager.removeBearer.secret }}
  namespace: {{ .Values.namespace }}
data:
  apicast-policy.json: ewogICAgIiRzY2hlbWEiOiAiaHR0cDovL2FwaWNhc3QuaW8vcG9saWN5LXYxL3NjaGVtYSNtYW5pZmVzdCMiLAogICAgIm5hbWUiOiAiUmVtb3ZlcyBCZWFyZXIgZnJvbSBBdXRob3JpemF0aW9uIFBvbGljeSIsCiAgICAic3VtbWFyeSI6ICJSZW1vdmVzICdCZWFyZXInIGluIEF1dGhvcml6YXRpb24gaGVhZGVyLiIsCiAgICAiZGVzY3JpcHRpb24iOiAiVGhpcyBwb2xpY3kgcmVtb3ZlcyAnQmVhcmVyJyBzZW50IGluIGFuIEF1dGhvcml6YXRpb24gaGVhZGVyIHNvIHRoYXQgdGhlIGFwaV9rZXkgaXMgcmVjb2duaXplZCBhcyBhIHRva2VuLiIsCiAgICAidmVyc2lvbiI6ICIwLjEiLAogICAgImNvbmZpZ3VyYXRpb24iOiB7CiAgICAgICJ0eXBlIjogIm9iamVjdCIsCiAgICAgICJwcm9wZXJ0aWVzIjogeyB9CiAgICB9CiAgfQ==
  init.lua: cmV0dXJuIHJlcXVpcmUoJ3JlbW92ZS1iZWFyZXInKQo=
  remove-bearer.lua: bG9jYWwgX00gPSByZXF1aXJlKCdhcGljYXN0LnBvbGljeScpLm5ldygnUmVtb3ZlIEJlYXJlcicsJzAuMScpCgpmdW5jdGlvbiBfTTpyZXdyaXRlKGNvbnRleHQpCiAgICBsb2NhbCBhdXRob3JpemF0aW9uID0gbmd4LnJlcS5nZXRfaGVhZGVycygpWyJBdXRob3JpemF0aW9uIl0KICAgIGlmIGF1dGhvcml6YXRpb24gYW5kIGF1dGhvcml6YXRpb246ZmluZCgiQmVhcmVyICIpIHRoZW4KICAgICAgICBsb2NhbCBuZXdfYXV0aG9yaXphdGlvbiA9IGF1dGhvcml6YXRpb246Z3N1YigiQmVhcmVyICIsICIiKQogICAgICAgIG5neC5yZXEuc2V0X2hlYWRlcigiQXV0aG9yaXphdGlvbiIsIG5ld19hdXRob3JpemF0aW9uKQogICAgZW5kCmVuZAoKcmV0dXJuIF9NCg==
{{- end }}
