{{- range .Values.user }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
type: Opaque
stringData:
  username: {{ .name }}
  password: openshift
---
apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  orgName: {{ .name }}
---
kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  developerAccountRef:
    name: {{ .name }}
  email: user1@example.com
  passwordCredentialsRef:
    name: {{ .name }}
  role: admin
  username: {{ .name }}
{{- end }}