{{- range .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-pwd
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
type: Opaque
stringData:
  password: {{ .password }}
---
apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: {{ .name }}-account
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  orgName: "{{ .name }}"
---
kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  username: {{ .name }}
  email: {{ .name }}@domain.com
  role: admin
  passwordCredentialsRef:
    name: {{ .name }}-pwd
  developerAccountRef:
    name: {{ .name }}-account
{{- end }}
